name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt -c deno.json --check

      - name: Run linter
        run: deno lint -c deno.json

  build:
    needs: test

    name: Build site
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run lume build
        run: deno task build
        env:
          BUILD_MODE: prod

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: praswicaksono.pw
          import-map: "./import_map.json"
          entrypoint: serve.ts
